package:
  name: fastcache
  version: 0.1

source:
  git_url : https://github.com/pbrady/fastcache.git
#  git_tag : a2534c47226760e0d51306ff5d32e06d3b503d6e
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - sympy = sympy:main
    #
    # Would create an entry point called sympy that calls sympy.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - fastcache
    - fastcache.lrucache
    - fastcache.clrucache

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/pbrady/fastcache.git
  license: MIT License
  summary: 'C implementation of Python 3 lru_cache'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
