package:
  name: fastcache
  version: 0.3.1

source:
   git_url : https://github.com/pbrady/fastcache.git

build:
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools    

  run:
    - python

test:
  # Python imports
  imports:
    - fastcache
    - fastcache.clru_cache
    - fastcache.lru_cache


about:
  home: https://github.com/pbrady/fastcache.git
  license: MIT License
  summary: 'C implementation of Python 3 lru_cache'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
